name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}

jobs:
  test:
    name: Node 12.x - ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn lint
      - run: yarn test

  nodeX:
    name: Node ${{ matrix.node-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10

    needs: [test]

    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [10.x, 12.x, 14.x, 16.x]

        # excluded because it is the `test` job above
        exclude:
          - os: ubuntu
            node-version: 12.x

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - run: yarn test

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: [test]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: 14.x

      - name: install dependencies
        run: yarn install --no-lockfile

      - run: yarn test
